@extends('layouts.marketing')
@section('title', 'Disclaimer — Merqio POS')
@section('meta_description', 'Important disclaimers regarding statutory calculations, third-party payment providers, and the limits of the Merqio POS platform.')

@section('content')

<section class="mkt-page-hero">
    <div class="mkt-container">
        <span class="mkt-eyebrow">Legal</span>
        <h1>Disclaimer</h1>
        <p>Important limitations you should understand before relying on the Platform.</p>
    </div>
</section>

<section class="mkt-section" style="padding-top:40px;">
    <div class="mkt-legal">
        <p class="mkt-legal-updated">Last updated: 28 August 2026 &nbsp;·&nbsp; Effective: 28 August 2026</p>

        <p>This Disclaimer supplements, and forms part of, our <a href="{{ route('terms') }}">Terms of Service</a>. It sets out important limitations on the information, calculations, and services provided through the Merqio POS platform at <strong>merqiopos.com</strong> (the "Platform"), operated by Merqio POS ("we", "us", "our"). Please read it carefully alongside our Terms of Service and <a href="{{ route('privacy') }}">Privacy Policy</a>. Capitalised terms not defined here have the meaning given to them in our Terms of Service.</p>

        <h2>1. General Disclaimer</h2>
        <p>The Platform is provided on an <strong>"as is"</strong> and <strong>"as available"</strong> basis. While we take reasonable care in developing and maintaining the Platform, we make no representation or warranty of any kind, express or implied, as to the operation of the Platform, the information, content, or materials included on it, or its fitness for any particular purpose, except to the extent such a warranty cannot lawfully be excluded. Your use of the Platform, and any reliance you place on such information, is strictly at your own risk.</p>

        <h2>2. Not Financial, Tax, Accounting, or Legal Advice</h2>
        <p>The Platform is a business management and record-keeping tool. Nothing on the Platform, including any report, calculation, summary, or notification it generates, constitutes financial, tax, accounting, legal, or other professional advice. It is not a substitute for consultation with a qualified accountant, tax advisor, lawyer, or other licensed professional. You should independently verify any figure, filing, or business decision with an appropriately qualified professional before relying on it, particularly for statutory filings, tax returns, or matters with legal or financial consequences.</p>

        <h2>3. Statutory Tax and Payroll Calculations</h2>
        <p>The Platform includes tools that compute figures such as Pay As You Earn (PAYE), National Social Security Fund (NSSF) contributions, Social Health Insurance Fund (SHIF) deductions, and Value Added Tax (VAT), based on rates, bands, and formulas that we believe to be current at the time they were last configured in the Platform.</p>
        <ul>
            <li>Kenyan statutory rates, bands, reliefs, and thresholds are set by the Kenya Revenue Authority (KRA), the National Social Security Fund, the Social Health Authority, and other government bodies, and are subject to change, sometimes with limited notice.</li>
            <li>We make reasonable efforts to keep these calculations up to date but do not guarantee that they reflect the most recent legislative or regulatory changes at all times.</li>
            <li>You are solely responsible for verifying that all statutory calculations, deductions, and filings generated using the Platform are accurate and comply with the law in force at the relevant time, before submitting any return, payslip, or payment based on them.</li>
            <li>We are not liable for any penalty, interest, fine, underpayment, overpayment, or other loss arising from reliance on a statutory calculation produced by the Platform that was, or later became, inaccurate or out of date.</li>
        </ul>

        <h2>4. Invoices, Tax Documents, and Compliance</h2>
        <p>Invoices, receipts, and other documents generated by the Platform are populated using the information you configure and enter, including your KRA PIN and VAT registration status. We do not verify the accuracy or validity of any tax registration number or rate you provide, and we do not confirm that documents generated by the Platform satisfy KRA requirements for any specific transaction or industry. You are responsible for ensuring your use of the Platform complies with all applicable tax, licensing, and industry-specific regulatory requirements relevant to your business (for example, additional requirements that may apply to pharmacies, food businesses, or financial service providers).</p>

        <h2>5. Third-Party Payment Processors</h2>
        <p>Merqio POS is not a bank, payment institution, or money remittance provider, and does not hold, custody, or have access to your funds at any time. Payments made or received through the Platform are processed entirely by independent third-party providers — principally Safaricom's M-Pesa (via the Daraja API) and, where enabled, Pesapal — directly into your own M-Pesa Paybill/Till or Pesapal merchant account. We merely relay payment instructions and read confirmation status from these providers.</p>
        <p>We are not responsible for: delays, failures, reversals, or errors in payment processing caused by these providers, mobile network operators, or banking infrastructure; incorrect account or till numbers configured by you; disputes between you and your customer regarding a payment; or the security practices of these third parties beyond our own integration with them. Any issue with a specific payment should also be raised directly with the relevant provider.</p>

        <h2>6. SMS and Communication Delivery</h2>
        <p>SMS and other notifications sent through the Platform are delivered via third-party gateway providers and depend on mobile network availability. We do not guarantee delivery, delivery time, or receipt of any message sent through the Platform, and are not liable for any consequence of a message being delayed or not delivered.</p>

        <h2>7. No Guarantee of Uninterrupted Availability</h2>
        <p>While we target the availability described in our Terms of Service, we do not warrant that the Platform will be uninterrupted, error-free, or free of harmful components at all times. Access may be affected by factors outside our control, including internet connectivity, third-party service outages, or scheduled maintenance. You should maintain your own reasonable business continuity practices (such as periodic data exports) and should not treat the Platform as a substitute for statutory bookkeeping records you are separately required to maintain.</p>

        <h2>8. Illustrative Content and Marketing Claims</h2>
        <p>Descriptions of business types, use cases, feature capabilities, and outcomes referenced on our marketing pages are illustrative and general in nature. They describe how the Platform is designed to be used and do not guarantee any specific result, revenue outcome, time saving, or business outcome for your particular business, which will depend on your own circumstances, industry, and how you use the Platform.</p>

        <h2>9. Third-Party Links</h2>
        <p>The Platform and our website may contain links to third-party websites or services (for example, a payment provider's checkout page) that are not owned or controlled by us. We have no control over, and assume no responsibility for, the content, privacy policies, or practices of any third-party website or service. Accessing a linked site is at your own risk.</p>

        <h2>10. Limitation of Liability</h2>
        <p>The limitations of liability set out in our <a href="{{ route('terms') }}">Terms of Service</a>, including the exclusions of indirect and consequential loss and the cap on our aggregate liability, apply equally to any claim arising out of or related to this Disclaimer, to the maximum extent permitted by Kenyan law.</p>

        <h2>11. Errors and Omissions</h2>
        <p>While we take reasonable steps to ensure information presented on the Platform and our website is accurate, we do not warrant that it is complete, current, or free of errors. If you notice an error, please report it to us using the contact details below so we can investigate and correct it.</p>

        <h2>12. Changes to This Disclaimer</h2>
        <p>We may update this Disclaimer from time to time, including to reflect changes in statutory rates, our third-party providers, or applicable law. Material changes will be notified in the same manner as changes to our Terms of Service. The "Last updated" date at the top of this page reflects the most recent revision.</p>

        <h2>13. Contact</h2>
        <p>If you have questions about this Disclaimer, please contact us:</p>
        <ul>
            <li>Email: <a href="mailto:support@merqiopos.com">support@merqiopos.com</a></li>
            <li>Phone / WhatsApp: <a href="tel:+254718215432">+254 718 215 432</a></li>
            <li>Address: Nairobi, Kenya</li>
        </ul>
    </div>
</section>

@endsection
