<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>P9 Form - {{ $staffProfile->user->name }} - {{ $year }}</title>
<style>
body { font-family: Arial, sans-serif; font-size: 10pt; margin: 20px; color: #000; }
h1 { font-size: 14pt; text-align: center; margin-bottom: 4px; }
.subtitle { text-align: center; font-size: 10pt; margin-bottom: 20px; color: #555; }
.section-header { background: #000; color: #fff; padding: 4px 8px; margin: 16px 0 8px; font-weight: bold; font-size: 10pt; }
table { width: 100%; border-collapse: collapse; margin-bottom: 12px; }
th, td { border: 1px solid #000; padding: 4px 6px; font-size: 9pt; }
th { background: #eee; font-weight: bold; }
.info-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; margin-bottom: 16px; }
.info-block { border: 1px solid #ccc; padding: 10px; }
.info-block strong { display: block; margin-bottom: 6px; }
.total-row { font-weight: bold; background: #f0f0f0; }
.text-right { text-align: right; }
</style>
</head>
<body>
<h1>EMPLOYEE'S P9 FORM</h1>
<div class="subtitle">Tax Year: {{ $year }} | Kenya Revenue Authority</div>

<div class="info-grid">
<div class="info-block">
<strong>EMPLOYER DETAILS</strong>
Name: {{ $business->name }}<br>
KRA PIN: {{ $business->kra_pin ?? 'N/A' }}<br>
Address: {{ $business->address ?? 'N/A' }}
</div>
<div class="info-block">
<strong>EMPLOYEE DETAILS</strong>
Name: {{ $staffProfile->user->name }}<br>
KRA PIN: {{ $staffProfile->kra_pin ?? 'N/A' }}<br>
NSSF No: {{ $staffProfile->nssf_no ?? 'N/A' }}
</div>
</div>

<div class="section-header">SECTION A — MONTHLY EARNINGS AND DEDUCTIONS</div>
<table>
<thead><tr>
    <th>Month</th>
    <th class="text-right">Gross Pay (KSh)</th>
    <th class="text-right">PAYE (KSh)</th>
    <th class="text-right">Personal Relief</th>
    <th class="text-right">Net PAYE</th>
    <th class="text-right">NSSF</th>
    <th class="text-right">SHIF</th>
    <th class="text-right">Net Pay</th>
</tr></thead>
<tbody>
@foreach($items as $item)
<tr>
    <td>{{ $item->label ?? \Carbon\Carbon::parse($item->period_start)->format('M Y') }}</td>
    <td class="text-right">{{ number_format($item->gross_pay, 2) }}</td>
    <td class="text-right">{{ number_format($item->paye + 2400, 2) }}</td>
    <td class="text-right">2,400.00</td>
    <td class="text-right">{{ number_format($item->paye, 2) }}</td>
    <td class="text-right">{{ number_format($item->nssf_employee, 2) }}</td>
    <td class="text-right">{{ number_format($item->shif, 2) }}</td>
    <td class="text-right">{{ number_format($item->net_pay, 2) }}</td>
</tr>
@endforeach
<tr class="total-row">
    <td><strong>TOTAL</strong></td>
    <td class="text-right">{{ number_format($totals['gross_pay'], 2) }}</td>
    <td class="text-right">{{ number_format($totals['paye'] + $totals['personal_relief'], 2) }}</td>
    <td class="text-right">{{ number_format($totals['personal_relief'], 2) }}</td>
    <td class="text-right">{{ number_format($totals['paye'], 2) }}</td>
    <td class="text-right">{{ number_format($totals['nssf_employee'], 2) }}</td>
    <td class="text-right">{{ number_format($totals['shif'], 2) }}</td>
    <td class="text-right">{{ number_format($totals['net_pay'], 2) }}</td>
</tr>
</tbody>
</table>

<div class="section-header">SECTION B — ANNUAL SUMMARY</div>
<table>
<tr><td><strong>Total Gross Pay</strong></td><td class="text-right">KSh {{ number_format($totals['gross_pay'], 2) }}</td></tr>
<tr><td><strong>Total Tax Charged (before relief)</strong></td><td class="text-right">KSh {{ number_format($totals['paye'] + $totals['personal_relief'], 2) }}</td></tr>
<tr><td><strong>Total Personal Relief</strong></td><td class="text-right">KSh {{ number_format($totals['personal_relief'], 2) }}</td></tr>
<tr><td><strong>Total PAYE Remitted</strong></td><td class="text-right">KSh {{ number_format($totals['paye'], 2) }}</td></tr>
<tr><td><strong>Total NSSF (Employee)</strong></td><td class="text-right">KSh {{ number_format($totals['nssf_employee'], 2) }}</td></tr>
<tr><td><strong>Total SHIF</strong></td><td class="text-right">KSh {{ number_format($totals['shif'], 2) }}</td></tr>
@if($totals['helb'] > 0)
<tr><td><strong>Total HELB Deductions</strong></td><td class="text-right">KSh {{ number_format($totals['helb'], 2) }}</td></tr>
@endif
<tr class="total-row"><td><strong>Total Net Pay</strong></td><td class="text-right">KSh {{ number_format($totals['net_pay'], 2) }}</td></tr>
</table>

<p style="margin-top:30px;font-size:9pt;color:#555;">This P9 form has been generated by {{ $business->name }} for the tax year {{ $year }}. Please verify with your HR department before filing with KRA.</p>
<p style="font-size:9pt;"><strong>Generated:</strong> {{ now()->format('d M Y H:i') }}</p>
</body>
</html>
